QT.mqtt_private.VERSION = 5.15.0
QT.mqtt_private.name = QtMqtt
QT.mqtt_private.module =
QT.mqtt_private.libs = $$QT_MODULE_LIB_BASE
QT.mqtt_private.includes = $$QT_MODULE_INCLUDE_BASE/QtMqtt/5.15.0 $$QT_MODULE_INCLUDE_BASE/QtMqtt/5.15.0/QtMqtt
QT.mqtt_private.frameworks =
QT.mqtt_private.depends = mqtt
QT.mqtt_private.uses =
QT.mqtt_private.module_config = v2 internal_module
QT.mqtt_private.enabled_features =
QT.mqtt_private.disabled_features =